name: Deploy Versioned API
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-versioned-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir data || true
      - run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::762706324393:role/github-actions-estate-id-deploy
      - run: NODE_OPTIONS="--max-old-space-size=4096" node bin/build.js
      - run: node bin/build-api.js
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - run: echo "${{ steps.get_version.outputs.VERSION }}"
      - name: S3 sync
        working-directory: api
        run: aws s3 sync . s3://geolonia-japanese-addresses/${{ steps.get_version.outputs.VERSION }} --cache-control "public, max-age=604800, immutable"
