name: Deploy Versioned API
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-versioned-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir data || true
      - run: npm install
      - run: NODE_OPTIONS="--max-old-space-size=4096" node bin/build.js
      - run: node bin/build-api.js
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - run: echo "${{ steps.get_version.outputs.VERSION }}"
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        working-directory: api
        run: aws s3 sync . s3://${{ secrets.AWS_BUCKET_NAME }}/${{ steps.get_version.outputs.VERSION }} --cache-control "public, max-age=604800, immutable"
      - name: Deploy generated files
        run: |
          git checkout --orphan gh-pages
          mkdir docs
          mv _config.yml docs/
          mv README.md docs/
          mv data/latest.db docs/
          mv data/latest.csv docs/
          mv api docs/
          mv images docs/
          git rm -rf . > /dev/null 2>&1
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add docs > /dev/null 2>&1
          git commit -m "Deploy" > /dev/null 2>&1
          git push --force origin gh-pages
