name: Deploy Versioned API
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-versioned-api:
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::762706324393:role/github-actions-geolonia-deploy

      - run: mkdir data || true

      - run: npm install

      - run: NODE_OPTIONS="--max-old-space-size=4096" node bin/build.js

      - run: node bin/build-api.js

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - run: echo "${{ steps.get_version.outputs.VERSION }}"

      - name: S3 sync
        working-directory: api
        run: aws s3 sync . s3://geolonia-japanese-addresses/${{ steps.get_version.outputs.VERSION }} --cache-control "public, max-age=604800, immutable"
